[package]
name = "fltk-smarttable-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1", features = ["fltk-bundled"] }
fltk-table = "0.2"
fltk-theme = "0.4"
chrono = "0.4"
